name = "snip-ly-worker"
main = "worker.js"
compatibility_date = "2025-02-06"

[vars]
CORS_ORIGIN = "*"
SHORT_DOMAIN = ""

[[d1_databases]]
binding = "DB"
database_name = "snip-ly-db"
database_id = "ded1962f-4f68-4843-bb65-4021e01c43c8"


